feat: add new ressources to the ontological database
okp4/ontology pull request #107
Opened 2023-03-31 09:21 UTC by CedrickArmel

add new ressources to the ontological database.

2023-03-31 11:29 UTC, ccamel requested changes

2023-03-31 11:29 UTC, ccamel commented on example/rhizome/dataset/0ea1fc7a-dd97-4adc-a10e-169c6597bcde.ttl
> +    core:hasLience license:LO-FR-1_0 ;
Typo:

```suggestion
    core:hasLicense license:LO-FR-1_0 ;
```

2023-03-31 15:43 UTC, ccamel approved these changes
LGTM! Thanks.

2023-03-31 16:18 UTC, MdechampG approved these changes

2023-04-03 11:57 UTC, ccamel commented
@CedrickArmel It's all good. FYI I renamed your commit to include the prefix `docs(example)` since the changes were related to documentation rather than features. :relieved:

2023-04-03 11:59 UTC, merged