feat : add governance
okp4/ontology pull request #174
Opened 2023-08-30 11:26 UTC by Gab-pm

upload governance rules for APPEL AGRI

2023-08-30 14:41 UTC, fredericvilcot commented
@Gab-pm 
I made some fixes to make the PR reviewable, looks good now 👍

2023-08-30 14:53 UTC, fredericvilcot approved these changes
LGTM!

2023-08-30 14:58 UTC, ccamel requested changes

2023-08-30 14:58 UTC, ccamel commented on example/appelagri/governance.ttl
> +    core:hasDescription "did:key:7u9401g1b7g1a7a28f9a5a239c326a9813a22f5a5b5d5f5e5d5c5b5a478998568"@en ;
There should be only one description per Paragraph for a considered language. Bascally a `Paragraph` has a single description, a free form expressed in a language (en, fr), which specifies the most elementary conditions that an article to which these rules relate must satisfy. Worth noting that the description supports markdown.

2023-08-30 14:59 UTC, ccamel commented on example/appelagri/governance.ttl
> +    core:hasDescription "did:key:7u9401g1b7g1a7a28f9a5a239c326a9813a22f5a5b5d5f5e5d5c5b5a478998568"@en ;
I think it would be interesting to add a unit test to cover this requirement (cf: hello https://github.com/okp4/ontology/issues/103).

2023-08-31 08:59 UTC, fredericvilcot approved these changes
LGTM!

2023-08-31 09:04 UTC, ccamel approved these changes
Great! Thanks :+1:

2023-08-31 09:05 UTC, merged